import "./globals.css";

import { Toaster } from "@/components/ui/toaster";

import { Analytics } from "@vercel/analytics/react"
//Themeprovider
import { ThemeProvider } from "@/components/ThemeProvider";

//Font
import { Sen } from "next/font/google"
const SenFont = Sen({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
  display: "swap"
})
export const metadata = {
  title: "Motion App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="pt" suppressHydrationWarning>
      <body className={SenFont.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
            {children}    
          <Toaster/>
        </ThemeProvider>
        <Analytics/>
      </body>
    </html>
  );
}
